name: my_task_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  http: ^1.5.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets\fonts\GeneralSans-Regular.otf

dependency_overrides:
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5